# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ltfnuuU3r6K9rVWvtSUe3QZ00lUk7yVi0iQ2CSowOkL60XxfiUtOvg==,iv:NVfFTaB7BjVmgHL5OdD9b9bH7g77Hs48u13ih+HSnZQ=,tag:4krQ4Wwvn1zYbv2COo1RPw==,type:str]
sops:
  age:
    - recipient: age1pt6ve7kxcf7m56tgh29gv2tlk40jt3qx5dhxhpjjgn9902pp9sks43mkhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV2NMRHZxUUJ4bWc5SkJL
        Y0pBRlpkaFgyd2FWSGRWTWRKamp5NFRmdWtFCmhQK25hellJVlJvZWpWUW9YN1VP
        Y28xOXlpZG9Eb2VxZW9oMGVELytUeDgKLS0tIENPSDkwNHV0a1JQVnUyZ2lBQTdN
        ckpHdll4RW8venUxc1VwVjM3dEhoUTgKqN0VypAk8rU3ND3ppXhy21ZgywQUrWlu
        O4EQoVFp2R10i56Frica8TTt/YEYoCAnuJLPLm7OcNwS50GNhvwovA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T04:20:17Z"
  mac: ENC[AES256_GCM,data:C6RXlD+MatzAHFMw+xhhM691Hw/qn2xiZ0hLfB5irB1YUQUlWftnFZYul5d5f63PjWsaYUCOuOvrnclpBRs/cK/m6IXGtWOUOxrWIKBd18SxEY2p6u2bJirsmFd1StBqQuIlgB1X4V5hBsBZ10ocMoqVEIv2fvmybH3nlFtPL0o=,iv:DSWRCXThdk6yEN+TAAF28zMfD67XZHmpvbEadGprY3U=,tag:4d8LFecZnfwiIBNCpbis4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
