# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FEm17otRDhxdXbX3ZXIVuBfrGKwlImHt0P0O1GaCz5Y=,iv:umium0TNaGcdkN5lCPqqZSRmq0Kz5b15Gtt5hi825m8=,tag:go3T1AWcDk7k+bOevDyj/g==,type:str]
sops:
  age:
    - recipient: age1pt6ve7kxcf7m56tgh29gv2tlk40jt3qx5dhxhpjjgn9902pp9sks43mkhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXA0bHA1aDF2WHpuSWZH
        K1BaWUpvY2o4OVZ3QUpNUjRQc1h6R2w4czBJCjhWaGdaMTdUVTg1NldvOEdIVWl6
        T1pnZUN6MlFxcllxMVc5ajdhS1A5Yk0KLS0tIDVoczNRYXZ5bFlGSjg5V3oxV0JE
        cGlPMVBwcS84dHc5L3BRMFEvQXRsNFEKjida+6aN1B0PhMrAuwmlPMFr6qcDKy56
        kD35Z0BIegueGT9R5GQskVb8+DEECloQ3OwA0u3THuIW+mNafi861g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-08T01:59:59Z"
  mac: ENC[AES256_GCM,data:xBhAshJ0+zZ3OJGosk1ewEK2NOK2juJi6WQsfEIuDOr4x+ULVYl/bbkINRPAYspt4ev32NIpu7pAR9NsrPtV4j0Yv/LEYt4MTflIWdijaYpTa1Qbs4Ogbt1ZJ0HXDRihwGhZCbTnFSOckYEBMyARjJ0UOLKVDY23ghoFfJSmKpw=,iv:FkIk2m+Lvi6aMTk8MI4OSi0cyphVjMgYzS/KIhyfSTM=,tag:KSHd63WlQPn12rgBzfHyZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
