# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8gaGJJ0Wg48T6JDtFglyThEIwMUoD2gZMNfaModVLcw=,iv:8yfQ1RvlQVxLm3AMPDXOZZgaR+oTUg+FN6jGJ3ZKQrw=,tag:O8uJoN7G9wGLOfjgNTSbFA==,type:str]
sops:
  age:
    - recipient: age1pt6ve7kxcf7m56tgh29gv2tlk40jt3qx5dhxhpjjgn9902pp9sks43mkhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N1VRT2FyZ0YxVkNIb1ZH
        TVhSdGlFQUYxRFZ1NzhOS1hEY0RNUlAvclRvCm9nYlRSSlVFZk1pRXhDT0FKYnIw
        M3gxanRleXQvUnFjOG4wWlVvbGU4R1kKLS0tIFQ4Rjdxdy81NmxzODlIZGNwTFdM
        c1BTaDJScjJCdDBQOHpsKzZqanJyRzQKevMhe8eWwEIu72bRyut4slqhsOES9U5x
        2G9+8LsIyBrbex2kFnfPw+dgMW7F3DxoF1Ry3LKIRc3H25jXfKbRqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-07T22:24:21Z"
  mac: ENC[AES256_GCM,data:YWQLdIl6s5MCWmVaTMthrkJLdnLmpHQ+Gyb20v316hX2RZgL7t6hF4Er9pvXJF0qEDpvvnOHOV6QgKkyjrWa3LCo2mzKyaFV1N673vHrl5EIgh0/C6h8hZv7nEAQgu5gc4BLGnMEVH4ZgV3pTIR/ML+4FgJ4ePb8i+ESIoUAM94=,iv:7hblCW/U5JfKWcoDgwYX8uvY7gFLue7GmkKlldE8Uzk=,tag:YqJFf0vbCmqiGpOFiTfDwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
